namespace CebizPay.Domain.Support.Enums;

/// <summary>
/// Source origin of a message posted to a support ticket thread.
/// Model supports customer, Kola automated assistant, and administrative operators without requiring a SupportAgent role.
/// </summary>
public enum TicketMessageSenderType
{
    /// <summary>Message originated from the authenticated customer.</summary>
    Customer = 1,

    /// <summary>Automated message generated by the Kola triage chatbot or system events.</summary>
    Kola = 2,

    /// <summary>Administrative operator responding to customer inquiry.</summary>
    Admin = 3
}
